/**
 * Comprehensive Food-Drug Interaction Knowledge Base
 * Clinically documented interactions used as fallback when Hugging Face API is unavailable.
 * Sources: FDA, DrugBank, clinical pharmacology references.
 */

export interface KnowledgeEntry {
    drug: string;
    drugClass: string;
    food: string;
    riskLevel: 'mild' | 'moderate' | 'severe';
    mechanism: string;
    clinicalImpact: string;
    recommendations: string[];
    alternatives: string[];
    timing: string;
    evidenceLevel: 'high' | 'moderate' | 'low';
}

export const interactionDatabase: KnowledgeEntry[] = [
    // ─── ANTICOAGULANTS ───
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'spinach',
        riskLevel: 'severe',
        mechanism: 'Spinach is rich in Vitamin K, which directly counteracts warfarin\'s mechanism of inhibiting Vitamin K-dependent clotting factors (II, VII, IX, X).',
        clinicalImpact: 'Can reduce INR (International Normalized Ratio) significantly, leading to subtherapeutic anticoagulation and increased risk of blood clots, stroke, or pulmonary embolism.',
        recommendations: ['Maintain consistent Vitamin K intake — do not suddenly increase or decrease', 'Monitor INR more frequently if diet changes', 'Consult your anticoagulation clinic before major dietary changes'],
        alternatives: ['Lettuce (iceberg — low Vitamin K)', 'Cucumbers', 'Bell peppers', 'Tomatoes'],
        timing: 'Consistent daily intake is more important than avoidance',
        evidenceLevel: 'high',
    },
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'kale',
        riskLevel: 'severe',
        mechanism: 'Kale contains extremely high Vitamin K levels (~817 mcg per cup), which antagonizes warfarin\'s anticoagulant effect.',
        clinicalImpact: 'A single large serving can drop INR by 1-2 points within 24-48 hours, potentially causing treatment failure.',
        recommendations: ['Avoid large or variable portions of kale', 'If consumed, keep portions small and consistent', 'Report any dietary changes to your healthcare provider'],
        alternatives: ['Romaine lettuce', 'Arugula (moderate — small amounts OK)', 'Swiss chard (in small amounts)'],
        timing: 'Effects on INR can persist for 3-5 days after large consumption',
        evidenceLevel: 'high',
    },
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'broccoli',
        riskLevel: 'moderate',
        mechanism: 'Broccoli contains moderate Vitamin K (~89 mcg per cup cooked), which can reduce warfarin efficacy.',
        clinicalImpact: 'Moderate portions are generally safe if consumed consistently. Large or irregular intake can cause INR fluctuations.',
        recommendations: ['Keep broccoli intake consistent from week to week', 'Do not suddenly add large portions', 'Monitor INR if changing consumption patterns'],
        alternatives: ['Cauliflower (very low Vitamin K)', 'Zucchini', 'Summer squash'],
        timing: 'Maintain consistent intake rather than avoiding entirely',
        evidenceLevel: 'high',
    },
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'cranberry',
        riskLevel: 'moderate',
        mechanism: 'Cranberry juice may inhibit CYP2C9 enzyme, which metabolizes warfarin, leading to increased warfarin levels.',
        clinicalImpact: 'Can increase INR and bleeding risk. Several case reports of serious bleeding events.',
        recommendations: ['Limit cranberry juice to small amounts (< 8 oz/day)', 'Monitor INR if consuming cranberry products', 'Report unusual bruising or bleeding'],
        alternatives: ['Apple juice', 'Grape juice (white)', 'Pear juice'],
        timing: 'Avoid large quantities; effects may take 2-3 days to manifest',
        evidenceLevel: 'moderate',
    },
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'grapefruit',
        riskLevel: 'moderate',
        mechanism: 'Grapefruit inhibits CYP3A4 and may affect CYP2C9, potentially increasing warfarin plasma levels.',
        clinicalImpact: 'May modestly increase INR and bleeding risk. Effect is less dramatic than with statins but still clinically relevant.',
        recommendations: ['Limit grapefruit consumption', 'Monitor INR when adding or removing grapefruit from diet', 'Watch for signs of bleeding (bruising, gum bleeding)'],
        alternatives: ['Oranges', 'Lemons', 'Limes'],
        timing: 'Effects can persist for 24-72 hours after consumption',
        evidenceLevel: 'moderate',
    },
    {
        drug: 'warfarin',
        drugClass: 'Anticoagulant (Vitamin K antagonist)',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Acute alcohol intake inhibits warfarin metabolism (CYP2E1), increasing anticoagulant effect. Chronic alcohol use induces metabolism, reducing efficacy.',
        clinicalImpact: 'Acute: increased bleeding risk. Chronic: reduced anticoagulation. Binge drinking is particularly dangerous.',
        recommendations: ['Limit to 1-2 standard drinks per day maximum', 'Never binge drink while on warfarin', 'Maintain consistent alcohol intake patterns'],
        alternatives: ['Non-alcoholic beverages', 'Sparkling water with fruit'],
        timing: 'Acute effects within hours; chronic effects develop over weeks',
        evidenceLevel: 'high',
    },
    // ─── STATINS ───
    {
        drug: 'atorvastatin',
        drugClass: 'Statin (HMG-CoA reductase inhibitor)',
        food: 'grapefruit',
        riskLevel: 'severe',
        mechanism: 'Grapefruit contains furanocoumarins that irreversibly inhibit intestinal CYP3A4 enzyme, dramatically increasing atorvastatin bioavailability.',
        clinicalImpact: 'Can increase atorvastatin blood levels by 200-300%, significantly raising the risk of rhabdomyolysis (muscle breakdown), liver damage, and kidney failure.',
        recommendations: ['⚠️ Avoid grapefruit and grapefruit juice entirely', 'Also avoid pomelos and Seville oranges', 'Report any unexplained muscle pain, tenderness, or dark urine immediately'],
        alternatives: ['Oranges', 'Tangerines', 'Lemons', 'Limes', 'Apples'],
        timing: 'A single glass of grapefruit juice can affect drug levels for up to 72 hours',
        evidenceLevel: 'high',
    },
    {
        drug: 'simvastatin',
        drugClass: 'Statin (HMG-CoA reductase inhibitor)',
        food: 'grapefruit',
        riskLevel: 'severe',
        mechanism: 'Simvastatin is heavily metabolized by CYP3A4. Grapefruit\'s inhibition of this enzyme causes dramatic increases in drug exposure.',
        clinicalImpact: 'Can increase simvastatin levels by up to 1600% (16-fold). Highest rhabdomyolysis risk among statins with grapefruit.',
        recommendations: ['⚠️ Complete avoidance of grapefruit is mandatory', 'FDA has issued specific warnings for this combination', 'Seek immediate medical attention for muscle pain or weakness'],
        alternatives: ['Any citrus fruit except grapefruit, pomelo, and Seville oranges'],
        timing: 'Effects persist for up to 72 hours after grapefruit consumption',
        evidenceLevel: 'high',
    },
    {
        drug: 'lovastatin',
        drugClass: 'Statin (HMG-CoA reductase inhibitor)',
        food: 'grapefruit',
        riskLevel: 'severe',
        mechanism: 'Similar to simvastatin, lovastatin is extensively metabolized by CYP3A4 and highly susceptible to grapefruit interaction.',
        clinicalImpact: 'Grapefruit can increase lovastatin AUC by up to 1500%. Very high risk of myopathy and rhabdomyolysis.',
        recommendations: ['⚠️ Avoid grapefruit completely', 'Report muscle symptoms immediately', 'Consider switching to rosuvastatin or pravastatin if grapefruit is desired'],
        alternatives: ['Oranges', 'Berries', 'Apples'],
        timing: 'Avoid entirely — no safe timing window exists',
        evidenceLevel: 'high',
    },
    // ─── ACE INHIBITORS / ARBs ───
    {
        drug: 'lisinopril',
        drugClass: 'ACE Inhibitor',
        food: 'banana',
        riskLevel: 'moderate',
        mechanism: 'ACE inhibitors reduce aldosterone secretion, causing potassium retention. Bananas are high in potassium (~422mg each). Combined, they can cause dangerous hyperkalemia.',
        clinicalImpact: 'Risk of hyperkalemia (elevated blood potassium), which can cause cardiac arrhythmias, muscle weakness, and in severe cases, cardiac arrest.',
        recommendations: ['Limit high-potassium foods to moderate portions', 'Monitor serum potassium levels regularly', 'Watch for symptoms: muscle weakness, irregular heartbeat, numbness'],
        alternatives: ['Apples', 'Berries', 'Grapes', 'Pears'],
        timing: 'Cumulative effect — consistent moderation is key',
        evidenceLevel: 'high',
    },
    {
        drug: 'lisinopril',
        drugClass: 'ACE Inhibitor',
        food: 'orange',
        riskLevel: 'moderate',
        mechanism: 'Oranges and orange juice are high in potassium. Combined with ACE inhibitor-induced potassium retention, risk of hyperkalemia increases.',
        clinicalImpact: 'Moderate risk of elevated potassium, especially in patients with renal impairment or those also taking potassium supplements.',
        recommendations: ['Moderate orange juice intake', 'Avoid potassium-fortified juices', 'Regular blood potassium monitoring'],
        alternatives: ['Apple juice', 'Cranberry juice', 'Lemonade'],
        timing: 'Monitor with regular intake; avoid excessive consumption',
        evidenceLevel: 'moderate',
    },
    {
        drug: 'losartan',
        drugClass: 'Angiotensin II Receptor Blocker (ARB)',
        food: 'banana',
        riskLevel: 'moderate',
        mechanism: 'ARBs like losartan can increase potassium levels by blocking aldosterone release. High-potassium foods compound this effect.',
        clinicalImpact: 'Similar hyperkalemia risk as ACE inhibitors. Especially dangerous in patients with kidney disease.',
        recommendations: ['Limit potassium-rich foods', 'Regular serum potassium monitoring', 'Take medication consistency with meals'],
        alternatives: ['Apples', 'Peaches', 'Plums'],
        timing: 'Effects are cumulative — moderate daily intake',
        evidenceLevel: 'high',
    },
    // ─── DIABETES MEDICATIONS ───
    {
        drug: 'metformin',
        drugClass: 'Biguanide (Antidiabetic)',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Both metformin and alcohol independently increase lactic acid production. Together, they dramatically elevate the risk of lactic acidosis, a life-threatening condition.',
        clinicalImpact: 'Lactic acidosis can be fatal (mortality rate 30-50%). Also increases risk of severe hypoglycemia by impairing hepatic gluconeogenesis.',
        recommendations: ['⚠️ Avoid excessive alcohol consumption', 'Limit to 1 drink/day for women, 2 for men', 'Never drink on an empty stomach', 'Monitor blood glucose more frequently after drinking'],
        alternatives: ['Non-alcoholic beer', 'Sparkling water', 'Sugar-free mocktails'],
        timing: 'Risk is highest with binge drinking or heavy chronic use',
        evidenceLevel: 'high',
    },
    {
        drug: 'metformin',
        drugClass: 'Biguanide (Antidiabetic)',
        food: 'grapefruit',
        riskLevel: 'mild',
        mechanism: 'Metformin is not significantly metabolized by CYP enzymes, so grapefruit interaction is minimal. However, grapefruit may slightly affect absorption.',
        clinicalImpact: 'Minimal clinical significance. Metformin\'s pharmacokinetics are largely unaffected.',
        recommendations: ['Generally safe to consume', 'Monitor blood glucose as usual', 'No specific timing restrictions needed'],
        alternatives: ['No restrictions needed'],
        timing: 'No specific timing concerns',
        evidenceLevel: 'moderate',
    },
    // ─── THYROID MEDICATIONS ───
    {
        drug: 'levothyroxine',
        drugClass: 'Thyroid Hormone Replacement',
        food: 'soy',
        riskLevel: 'moderate',
        mechanism: 'Soy products contain isoflavones that can inhibit thyroid peroxidase and may reduce absorption of levothyroxine from the GI tract.',
        clinicalImpact: 'Can reduce levothyroxine efficacy by 20-30%, leading to subtherapeutic thyroid levels and hypothyroid symptoms.',
        recommendations: ['Space levothyroxine and soy products by at least 4 hours', 'Take levothyroxine on an empty stomach, 30-60 min before food', 'Monitor TSH levels if adding soy to diet'],
        alternatives: ['Almond milk', 'Oat milk', 'Rice milk'],
        timing: 'Take levothyroxine 4+ hours before soy consumption',
        evidenceLevel: 'high',
    },
    {
        drug: 'levothyroxine',
        drugClass: 'Thyroid Hormone Replacement',
        food: 'coffee',
        riskLevel: 'moderate',
        mechanism: 'Coffee accelerates gastric emptying and can reduce levothyroxine absorption by up to 36% when taken simultaneously.',
        clinicalImpact: 'Reduces drug absorption, potentially causing subtherapeutic thyroid levels and persistent hypothyroid symptoms despite adequate dosing.',
        recommendations: ['Wait at least 60 minutes after taking levothyroxine before drinking coffee', 'Take levothyroxine with plain water only', 'Consider thyroid liquid formulation if timing is difficult'],
        alternatives: ['Wait 60 min, then coffee is fine', 'Herbal tea after waiting period'],
        timing: 'Wait minimum 60 minutes between levothyroxine and coffee',
        evidenceLevel: 'high',
    },
    {
        drug: 'levothyroxine',
        drugClass: 'Thyroid Hormone Replacement',
        food: 'milk',
        riskLevel: 'moderate',
        mechanism: 'Calcium in milk forms insoluble complexes with levothyroxine, reducing drug absorption by 20-40%.',
        clinicalImpact: 'Significant reduction in drug bioavailability, leading to inadequate thyroid hormone replacement.',
        recommendations: ['Separate levothyroxine from dairy by at least 4 hours', 'Take levothyroxine on empty stomach with water', 'Calcium supplements should also be separated by 4 hours'],
        alternatives: ['Take medication first, dairy later', 'Plant-based milks (almond, oat) have less calcium interference'],
        timing: 'Space by 4+ hours',
        evidenceLevel: 'high',
    },
    // ─── CALCIUM CHANNEL BLOCKERS ───
    {
        drug: 'amlodipine',
        drugClass: 'Calcium Channel Blocker',
        food: 'grapefruit',
        riskLevel: 'moderate',
        mechanism: 'Grapefruit inhibits CYP3A4-mediated first-pass metabolism of amlodipine, increasing drug bioavailability.',
        clinicalImpact: 'Can increase amlodipine levels by 15-20%, potentially causing excessive blood pressure lowering, dizziness, headache, and peripheral edema.',
        recommendations: ['Limit grapefruit intake or avoid during dose adjustment periods', 'Monitor blood pressure regularly', 'Report symptoms of hypotension (dizziness, lightheadedness)'],
        alternatives: ['Oranges', 'Mandarins', 'Lemons'],
        timing: 'Effects persist 24-48 hours after grapefruit consumption',
        evidenceLevel: 'moderate',
    },
    {
        drug: 'felodipine',
        drugClass: 'Calcium Channel Blocker',
        food: 'grapefruit',
        riskLevel: 'severe',
        mechanism: 'Felodipine is one of the most affected drugs by grapefruit. CYP3A4 inhibition increases bioavailability dramatically.',
        clinicalImpact: 'Can increase felodipine levels by 200-300%, causing severe hypotension, tachycardia, and facial flushing.',
        recommendations: ['⚠️ Avoid grapefruit completely while on felodipine', 'This is a well-documented severe interaction', 'Seek medical attention for severe dizziness or fainting'],
        alternatives: ['Any citrus except grapefruit and pomelo'],
        timing: 'Avoid entirely — no safe timing window',
        evidenceLevel: 'high',
    },
    // ─── ANTIBIOTICS ───
    {
        drug: 'tetracycline',
        drugClass: 'Antibiotic',
        food: 'milk',
        riskLevel: 'severe',
        mechanism: 'Calcium, magnesium, and iron in dairy products form insoluble chelates with tetracycline, preventing absorption.',
        clinicalImpact: 'Can reduce antibiotic absorption by 50-90%, leading to treatment failure and potential antibiotic resistance development.',
        recommendations: ['⚠️ Take tetracycline 1 hour before or 2 hours after dairy', 'Avoid calcium supplements around dosing time', 'Do not take with antacids containing calcium/magnesium'],
        alternatives: ['Water', 'Clear juices without calcium fortification'],
        timing: 'Separate by at least 2 hours before or after dairy',
        evidenceLevel: 'high',
    },
    {
        drug: 'ciprofloxacin',
        drugClass: 'Fluoroquinolone Antibiotic',
        food: 'milk',
        riskLevel: 'moderate',
        mechanism: 'Calcium in dairy chelates with ciprofloxacin, reducing absorption. However, ciprofloxacin can be taken with a meal containing some dairy.',
        clinicalImpact: 'Dairy alone can reduce ciprofloxacin absorption by 30-36%. Calcium-fortified juices have similar effects.',
        recommendations: ['Do not take ciprofloxacin with dairy products alone', 'May take with a meal that includes some dairy', 'Avoid calcium-fortified beverages around dosing'],
        alternatives: ['Take with a full meal', 'Water', 'Non-fortified juices'],
        timing: 'Separate from standalone dairy by 2 hours',
        evidenceLevel: 'high',
    },
    {
        drug: 'doxycycline',
        drugClass: 'Tetracycline Antibiotic',
        food: 'milk',
        riskLevel: 'moderate',
        mechanism: 'Calcium in dairy can chelate with doxycycline, though less affected than tetracycline. Absorption reduced by 20-30%.',
        clinicalImpact: 'Moderate reduction in drug absorption. Less severe than with tetracycline but still clinically meaningful.',
        recommendations: ['Space doxycycline from dairy by 2 hours', 'Take with water and a non-dairy snack if needed', 'Complete full course of antibiotics as prescribed'],
        alternatives: ['Non-dairy milk alternatives', 'Water'],
        timing: 'Space by 2 hours before or after dairy',
        evidenceLevel: 'moderate',
    },
    // ─── PROTON PUMP INHIBITORS ───
    {
        drug: 'omeprazole',
        drugClass: 'Proton Pump Inhibitor',
        food: 'coffee',
        riskLevel: 'mild',
        mechanism: 'Coffee increases stomach acid production, which may partially counteract omeprazole\'s acid-suppressing effect.',
        clinicalImpact: 'Minor reduction in clinical efficacy. May worsen GERD symptoms or heartburn despite medication.',
        recommendations: ['Limit coffee intake if experiencing breakthrough acid reflux', 'Take omeprazole 30 minutes before breakfast', 'Consider decaf alternatives'],
        alternatives: ['Decaf coffee', 'Low-acid coffee brands', 'Herbal teas (non-mint)'],
        timing: 'Take omeprazole before morning coffee',
        evidenceLevel: 'moderate',
    },
    {
        drug: 'omeprazole',
        drugClass: 'Proton Pump Inhibitor',
        food: 'alcohol',
        riskLevel: 'moderate',
        mechanism: 'Alcohol irritates gastric mucosa and increases acid production, counteracting PPI therapy. Omeprazole may also slightly slow alcohol metabolism.',
        clinicalImpact: 'Reduced PPI efficacy and worsened gastric symptoms. May result in higher blood alcohol levels.',
        recommendations: ['Limit alcohol consumption', 'Avoid drinking on an empty stomach', 'Monitor for increased GERD symptoms'],
        alternatives: ['Non-alcoholic beverages', 'Low-acid drinks'],
        timing: 'Minimize alcohol; take omeprazole as directed regardless',
        evidenceLevel: 'moderate',
    },
    // ─── ANTICONVULSANTS ───
    {
        drug: 'gabapentin',
        drugClass: 'Anticonvulsant/Neuropathic Pain Agent',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Both gabapentin and alcohol are CNS depressants. Combined, they potentiate sedative effects through additive GABA-ergic mechanisms.',
        clinicalImpact: 'Dangerous CNS depression causing extreme drowsiness, respiratory depression, impaired motor function, and potential loss of consciousness.',
        recommendations: ['⚠️ Avoid alcohol while taking gabapentin', 'Do not drive or operate machinery if consuming any alcohol', 'Inform your doctor about alcohol use'],
        alternatives: ['Non-alcoholic beverages only'],
        timing: 'Avoid alcohol entirely during gabapentin therapy',
        evidenceLevel: 'high',
    },
    {
        drug: 'phenytoin',
        drugClass: 'Anticonvulsant',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Acute alcohol increases phenytoin levels (CYP2E1 inhibition). Chronic alcohol decreases levels (enzyme induction). Both are dangerous for seizure control.',
        clinicalImpact: 'Unpredictable drug levels — either toxicity (nystagmus, ataxia, confusion) or subtherapeutic levels (seizure breakthrough).',
        recommendations: ['⚠️ Avoid alcohol completely', 'Maintain consistent medication schedule', 'Monitor phenytoin levels if alcohol exposure occurs'],
        alternatives: ['Non-alcoholic beverages only'],
        timing: 'Complete avoidance recommended',
        evidenceLevel: 'high',
    },
    // ─── DIURETICS ───
    {
        drug: 'hydrochlorothiazide',
        drugClass: 'Thiazide Diuretic',
        food: 'licorice',
        riskLevel: 'severe',
        mechanism: 'Natural licorice contains glycyrrhizin, which inhibits 11β-HSD2 enzyme, causing sodium retention and potassium loss — compounding HCTZ\'s potassium-wasting effect.',
        clinicalImpact: 'Severe hypokalemia risk, which can cause cardiac arrhythmias, muscle cramps, weakness, and potentially cardiac arrest.',
        recommendations: ['⚠️ Avoid natural licorice (glycyrrhizin-containing) products', 'Artificial licorice flavoring is safe', 'Monitor potassium levels if consumed accidentally'],
        alternatives: ['Artificially flavored licorice candy (check labels)', 'Other candy/snacks'],
        timing: 'Avoid natural licorice entirely',
        evidenceLevel: 'high',
    },
    {
        drug: 'furosemide',
        drugClass: 'Loop Diuretic',
        food: 'licorice',
        riskLevel: 'severe',
        mechanism: 'Same glycyrrhizin mechanism as with HCTZ. Loop diuretics cause even more potassium loss than thiazides, making this combination particularly dangerous.',
        clinicalImpact: 'High risk of life-threatening hypokalemia and cardiac arrhythmias.',
        recommendations: ['⚠️ Strictly avoid natural licorice', 'Ensure adequate potassium intake from other sources', 'Report muscle weakness or heart palpitations immediately'],
        alternatives: ['Artificially flavored products only'],
        timing: 'Complete avoidance',
        evidenceLevel: 'high',
    },
    // ─── MAO INHIBITORS ───
    {
        drug: 'phenelzine',
        drugClass: 'MAOI Antidepressant',
        food: 'cheese',
        riskLevel: 'severe',
        mechanism: 'Aged cheeses contain high tyramine levels. MAOIs prevent tyramine breakdown by monoamine oxidase, causing massive norepinephrine release.',
        clinicalImpact: 'Hypertensive crisis — sudden, dangerous blood pressure spike (>180/120) that can cause stroke, brain hemorrhage, or death.',
        recommendations: ['⚠️ AVOID all aged cheeses (cheddar, Swiss, Parmesan, blue cheese)', 'Fresh cheeses (cream cheese, cottage cheese) are generally safe', 'Seek emergency care for sudden severe headache or chest pain'],
        alternatives: ['Fresh mozzarella', 'Cream cheese', 'Cottage cheese', 'Ricotta'],
        timing: 'Avoid throughout MAOI therapy and 2 weeks after stopping',
        evidenceLevel: 'high',
    },
    {
        drug: 'tranylcypromine',
        drugClass: 'MAOI Antidepressant',
        food: 'wine',
        riskLevel: 'severe',
        mechanism: 'Red wine contains high tyramine levels. MAOI blockade prevents tyramine metabolism, causing a sympathomimetic storm.',
        clinicalImpact: 'Risk of hypertensive crisis identical to the cheese reaction. Red wine is particularly dangerous; white wine has lower tyramine.',
        recommendations: ['⚠️ Avoid red wine completely', 'White wine in very small amounts may be tolerable but risky', 'Carry emergency nifedipine as prescribed by doctor'],
        alternatives: ['Non-alcoholic beverages', 'Fresh fruit juices'],
        timing: 'Avoid during and 2 weeks after MAOI therapy',
        evidenceLevel: 'high',
    },
    // ─── ANTIDEPRESSANTS (SSRIs) ───
    {
        drug: 'sertraline',
        drugClass: 'SSRI Antidepressant',
        food: 'alcohol',
        riskLevel: 'moderate',
        mechanism: 'Alcohol has CNS depressant effects that combine with SSRI side effects. May also affect serotonin pathways unpredictably.',
        clinicalImpact: 'Increased sedation, impaired judgment, worsened depression symptoms, and potential serotonin-related effects.',
        recommendations: ['Limit alcohol consumption', 'Avoid alcohol when starting or adjusting dose', 'Monitor mood changes if drinking'],
        alternatives: ['Non-alcoholic social beverages', 'Sparkling water'],
        timing: 'Minimize alcohol; be cautious during dose changes',
        evidenceLevel: 'moderate',
    },
    // ─── IMMUNOSUPPRESSANTS ───
    {
        drug: 'cyclosporine',
        drugClass: 'Immunosuppressant',
        food: 'grapefruit',
        riskLevel: 'severe',
        mechanism: 'Grapefruit powerfully inhibits CYP3A4 and P-glycoprotein, dramatically increasing cyclosporine absorption and blood levels.',
        clinicalImpact: 'Can increase cyclosporine levels by 30-60%, causing nephrotoxicity (kidney damage), hypertension, and increased risk of infection.',
        recommendations: ['⚠️ Avoid grapefruit and related citrus completely', 'Monitor drug levels closely if accidental exposure', 'Report changes in urine output or blood pressure'],
        alternatives: ['Oranges', 'Apples', 'Berries'],
        timing: 'Complete avoidance — effects persist 72+ hours',
        evidenceLevel: 'high',
    },
    // ─── BENZODIAZEPINES ───
    {
        drug: 'alprazolam',
        drugClass: 'Benzodiazepine',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Both are CNS depressants acting on GABA-A receptors. Combined effect is synergistic, not merely additive.',
        clinicalImpact: 'Life-threatening respiratory depression, profound sedation, coma, and death. FDA black box warning exists for this combination.',
        recommendations: ['⚠️ NEVER combine with alcohol — FDA black box warning', 'Even small amounts of alcohol can be dangerous', 'Seek emergency care if both consumed'],
        alternatives: ['Absolutely no alcohol alternatives — complete avoidance required'],
        timing: 'Complete avoidance during entire benzodiazepine therapy',
        evidenceLevel: 'high',
    },
    {
        drug: 'diazepam',
        drugClass: 'Benzodiazepine',
        food: 'grapefruit',
        riskLevel: 'moderate',
        mechanism: 'Grapefruit inhibits CYP3A4 metabolism of diazepam, increasing drug levels and prolonging sedative effects.',
        clinicalImpact: 'Increased and prolonged sedation, impaired coordination, and higher fall risk.',
        recommendations: ['Avoid grapefruit while taking diazepam', 'Be cautious with driving or machinery', 'Report excessive drowsiness to your doctor'],
        alternatives: ['Oranges', 'Other citrus fruits'],
        timing: 'Avoid grapefruit throughout therapy',
        evidenceLevel: 'moderate',
    },
    // ─── OPIOIDS ───
    {
        drug: 'oxycodone',
        drugClass: 'Opioid Analgesic',
        food: 'alcohol',
        riskLevel: 'severe',
        mechanism: 'Synergistic CNS and respiratory depression. Alcohol also increases opioid absorption from extended-release formulations (dose dumping).',
        clinicalImpact: 'Fatal respiratory depression. Leading cause of prescription drug overdose deaths in combination.',
        recommendations: ['⚠️ NEVER combine with alcohol — risk of death', 'Even small amounts can be fatal', 'Call 911 immediately if both consumed and sleepiness occurs'],
        alternatives: ['No alcohol under any circumstances'],
        timing: 'Complete avoidance — this combination kills',
        evidenceLevel: 'high',
    },
    // ─── ANTIFUNGALS ───
    {
        drug: 'itraconazole',
        drugClass: 'Azole Antifungal',
        food: 'grapefruit',
        riskLevel: 'moderate',
        mechanism: 'Grapefruit inhibits CYP3A4, reducing itraconazole metabolism and increasing adverse effects.',
        clinicalImpact: 'Increased drug levels can cause GI symptoms, headache, and hepatotoxicity.',
        recommendations: ['Avoid grapefruit during treatment', 'Take with acidic beverages (cola) to improve absorption', 'Monitor for GI side effects'],
        alternatives: ['Cola', 'Orange juice', 'Cranberry juice'],
        timing: 'Avoid grapefruit throughout antifungal course',
        evidenceLevel: 'moderate',
    },
];

/**
 * Search the knowledge base for a matching interaction.
 */
export function findKnownInteraction(medication: string, food: string): KnowledgeEntry | null {
    const medLower = medication.toLowerCase().trim();
    const foodLower = food.toLowerCase().trim();

    for (const entry of interactionDatabase) {
        const drugMatch = medLower.includes(entry.drug) || entry.drug.includes(medLower);
        const foodMatch = foodLower.includes(entry.food) || entry.food.includes(foodLower);

        if (drugMatch && foodMatch) {
            return entry;
        }
    }
    return null;
}
